### ISSUE TITLE
pip3

### ISSUE THREAD

**Issue by pedromorgan** [fmalina/blocl-bnglatlon#4]
Can this project also be packages for python3 ??

pete

**Comment by pedromorgan** [comment]
```
 Downloading https://files.pythonhosted.org/packages/0f/16/5746a717e557f485425cd2dd1facff7a7da8135e559d543050b05ec790be/bng_latlon-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yo0eeykm/bng-latlon/setup.py", line 8, in <module>
        long_description=open('README.rst').read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yo0eeykm/bng-latlon/

```

**Comment by hellicott** [comment]
Same problem for me, it seems this repo hasn't been touched for 5 years so not sure it's being maintained anymore

**Comment by pedromorgan** [comment]
It's crazy how many projects like this have a **single maintainer** who then disappears.

**Comment by pedromorgan** [comment]
@fmalina U there ????

**Comment by fmalina** [comment]
I am here, lemme look

**Comment by fmalina** [comment]
What OS, works for me with pip3 on OS X and linux no problem

**Comment by fmalina** [comment]
It's all Python3

**Comment by pedromorgan** [comment]
@fmalina indeed it does now... strange (scratches head)

**Comment by fmalina** [comment]
Thanks, closing
